name: Continuous Integration

on:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:
    branches:
      - master
      - main
      - develop
      
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: 'maven'
      
      # Add your test command here.
      # This should be the command that you use when you run your tests locally.
      # Depending on your tooling, the command can come from maven, gradle, or your own custom script. 
      - name: Run tests
        run: mvn test 
